// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoFCy5W1WH20wCQcaxQBZYEOO61HKNTPI',
    appId: '1:641365738436:android:7c04b66216d4d44a361a91',
    messagingSenderId: '641365738436',
    projectId: 'cs6-mobile',
    storageBucket: 'cs6-mobile.firebasestorage.app',
  );

  static FirebaseOptions get currentPlatform => android;
}
